// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: tier2.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tier2Service_Query_FullMethodName       = "/tier2.Tier2Service/Query"
	Tier2Service_InjectError_FullMethodName = "/tier2.Tier2Service/InjectError"
)

// Tier2ServiceClient is the client API for Tier2Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Tier2ServiceClient interface {
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	InjectError(ctx context.Context, in *ErrorRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
}

type tier2ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTier2ServiceClient(cc grpc.ClientConnInterface) Tier2ServiceClient {
	return &tier2ServiceClient{cc}
}

func (c *tier2ServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, Tier2Service_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tier2ServiceClient) InjectError(ctx context.Context, in *ErrorRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, Tier2Service_InjectError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Tier2ServiceServer is the server API for Tier2Service service.
// All implementations must embed UnimplementedTier2ServiceServer
// for forward compatibility.
type Tier2ServiceServer interface {
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	InjectError(context.Context, *ErrorRequest) (*ErrorResponse, error)
	mustEmbedUnimplementedTier2ServiceServer()
}

// UnimplementedTier2ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTier2ServiceServer struct{}

func (UnimplementedTier2ServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedTier2ServiceServer) InjectError(context.Context, *ErrorRequest) (*ErrorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InjectError not implemented")
}
func (UnimplementedTier2ServiceServer) mustEmbedUnimplementedTier2ServiceServer() {}
func (UnimplementedTier2ServiceServer) testEmbeddedByValue()                      {}

// UnsafeTier2ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Tier2ServiceServer will
// result in compilation errors.
type UnsafeTier2ServiceServer interface {
	mustEmbedUnimplementedTier2ServiceServer()
}

func RegisterTier2ServiceServer(s grpc.ServiceRegistrar, srv Tier2ServiceServer) {
	// If the following call panics, it indicates UnimplementedTier2ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tier2Service_ServiceDesc, srv)
}

func _Tier2Service_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Tier2ServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tier2Service_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Tier2ServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tier2Service_InjectError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Tier2ServiceServer).InjectError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tier2Service_InjectError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Tier2ServiceServer).InjectError(ctx, req.(*ErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tier2Service_ServiceDesc is the grpc.ServiceDesc for Tier2Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tier2Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tier2.Tier2Service",
	HandlerType: (*Tier2ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _Tier2Service_Query_Handler,
		},
		{
			MethodName: "InjectError",
			Handler:    _Tier2Service_InjectError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tier2.proto",
}
