// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: tier2.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_tier2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tier2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_tier2_proto_rawDescGZIP(), []int{0}
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbOk          bool                   `protobuf:"varint,1,opt,name=db_ok,json=dbOk,proto3" json:"db_ok,omitempty"`
	DbRows        int32                  `protobuf:"varint,2,opt,name=db_rows,json=dbRows,proto3" json:"db_rows,omitempty"`
	DbDurationMs  int64                  `protobuf:"varint,3,opt,name=db_duration_ms,json=dbDurationMs,proto3" json:"db_duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_tier2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tier2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_tier2_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetDbOk() bool {
	if x != nil {
		return x.DbOk
	}
	return false
}

func (x *QueryResponse) GetDbRows() int32 {
	if x != nil {
		return x.DbRows
	}
	return 0
}

func (x *QueryResponse) GetDbDurationMs() int64 {
	if x != nil {
		return x.DbDurationMs
	}
	return 0
}

type ErrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorRequest) Reset() {
	*x = ErrorRequest{}
	mi := &file_tier2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorRequest) ProtoMessage() {}

func (x *ErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tier2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorRequest.ProtoReflect.Descriptor instead.
func (*ErrorRequest) Descriptor() ([]byte, []int) {
	return file_tier2_proto_rawDescGZIP(), []int{2}
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorMsg      string                 `protobuf:"bytes,1,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_tier2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tier2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_tier2_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_tier2_proto protoreflect.FileDescriptor

const file_tier2_proto_rawDesc = "" +
	"\n" +
	"\vtier2.proto\x12\x05tier2\"\x0e\n" +
	"\fQueryRequest\"c\n" +
	"\rQueryResponse\x12\x13\n" +
	"\x05db_ok\x18\x01 \x01(\bR\x04dbOk\x12\x17\n" +
	"\adb_rows\x18\x02 \x01(\x05R\x06dbRows\x12$\n" +
	"\x0edb_duration_ms\x18\x03 \x01(\x03R\fdbDurationMs\"\x0e\n" +
	"\fErrorRequest\",\n" +
	"\rErrorResponse\x12\x1b\n" +
	"\terror_msg\x18\x01 \x01(\tR\berrorMsg2|\n" +
	"\fTier2Service\x122\n" +
	"\x05Query\x12\x13.tier2.QueryRequest\x1a\x14.tier2.QueryResponse\x128\n" +
	"\vInjectError\x12\x13.tier2.ErrorRequest\x1a\x14.tier2.ErrorResponseB\x15Z\x13wide-events-demo/pbb\x06proto3"

var (
	file_tier2_proto_rawDescOnce sync.Once
	file_tier2_proto_rawDescData []byte
)

func file_tier2_proto_rawDescGZIP() []byte {
	file_tier2_proto_rawDescOnce.Do(func() {
		file_tier2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tier2_proto_rawDesc), len(file_tier2_proto_rawDesc)))
	})
	return file_tier2_proto_rawDescData
}

var file_tier2_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tier2_proto_goTypes = []any{
	(*QueryRequest)(nil),  // 0: tier2.QueryRequest
	(*QueryResponse)(nil), // 1: tier2.QueryResponse
	(*ErrorRequest)(nil),  // 2: tier2.ErrorRequest
	(*ErrorResponse)(nil), // 3: tier2.ErrorResponse
}
var file_tier2_proto_depIdxs = []int32{
	0, // 0: tier2.Tier2Service.Query:input_type -> tier2.QueryRequest
	2, // 1: tier2.Tier2Service.InjectError:input_type -> tier2.ErrorRequest
	1, // 2: tier2.Tier2Service.Query:output_type -> tier2.QueryResponse
	3, // 3: tier2.Tier2Service.InjectError:output_type -> tier2.ErrorResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tier2_proto_init() }
func file_tier2_proto_init() {
	if File_tier2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tier2_proto_rawDesc), len(file_tier2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tier2_proto_goTypes,
		DependencyIndexes: file_tier2_proto_depIdxs,
		MessageInfos:      file_tier2_proto_msgTypes,
	}.Build()
	File_tier2_proto = out.File
	file_tier2_proto_goTypes = nil
	file_tier2_proto_depIdxs = nil
}
